<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Jadwal;
use App\Models\User;

class JadwalSeeder extends Seeder
{
    public function run(): void
    {
        // Ambil ID user admin pertama untuk relasi user_id
        $admin = User::where('role', 'admin')->first();
        $adminId = $admin ? $admin->id : 1;

        $daftarJadwal = [
            // DATA MINING
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'DATA MINING',
                'dosen' => 'ZARA YUNIZAR, S.Kom.,M.Kom; LIDYA ROSNITA, S.T., M. Kom',
                'hari' => 'Kamis',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => 'INF-RUANG KULIAH IV',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'DATA MINING',
                'dosen' => 'ZARA YUNIZAR, S.Kom.,M.Kom; LIDYA ROSNITA, S.T., M. Kom',
                'hari' => 'Kamis',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => 'INF-RUANG KULIAH IV',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'DATA MINING',
                'dosen' => 'Prof. Dr.NURDIN, S.KOM, M.KOM; HAFIZH AL KAUTSAR AIDILOF, ST.,M.Kom',
                'hari' => 'Senin',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => '08.A',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'DATA MINING',
                'dosen' => 'Prof. Dr.NURDIN, S.KOM, M.KOM; HAFIZH AL KAUTSAR AIDILOF, ST.,M.Kom',
                'hari' => 'Senin',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => '08.A',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'DATA MINING',
                'dosen' => 'Prof. Dr.NURDIN, S.KOM, M.KOM; HAFIZH AL KAUTSAR AIDILOF, ST.,M.Kom',
                'hari' => 'Rabu',
                'jam_mulai' => '08:00',
                'jam_selesai' => '10:30',
                'ruangan' => 'INF-RUANG KULIAH MTI 1',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'DATA MINING',
                'dosen' => 'DrASRIANDA, S.Kom.,M.Kom; EVA DARNILA, ST.,MT',
                'hari' => 'Senin',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => 'INF-RUANG KULIAH II',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'DATA MINING',
                'dosen' => 'MARYANA, S.Si., M.Si; YESY AFRILLIA, ST.,M.Kom',
                'hari' => 'Senin',
                'jam_mulai' => '08:00',
                'jam_selesai' => '10:30',
                'ruangan' => 'INF-RUANG KULIAH III',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'DATA MINING',
                'dosen' => 'MARYANA, S.Si., M.Si; YESY AFRILLIA, ST.,M.Kom',
                'hari' => 'Senin',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => 'INF-RUANG KULIAH III',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'DATA MINING',
                'dosen' => 'MARYANA, S.Si., M.Si; YESY AFRILLIA, ST.,M.Kom',
                'hari' => 'Kamis',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => 'INF-RUANG KULIAH V',
            ],

            // DESAIN DAN ANALISIS ALGORITMA
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'DESAIN DAN ANALISIS ALGORITMA',
                'dosen' => 'Prof. Dr.NURDIN, S.KOM, M.KOM; HAFIZH AL KAUTSAR AIDILOF, ST.,M.Kom',
                'hari' => 'Senin',
                'jam_mulai' => '08:00',
                'jam_selesai' => '10:30',
                'ruangan' => 'INF-RUANG KULIAH V',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'DESAIN DAN ANALISIS ALGORITMA',
                'dosen' => 'Prof. Dr.NURDIN, S.KOM, M.KOM; HAFIZH AL KAUTSAR AIDILOF, ST.,M.Kom',
                'hari' => 'Senin',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => 'INF-RUANG KULIAH V',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'DESAIN DAN ANALISIS ALGORITMA',
                'dosen' => 'Prof. Dr.NURDIN, S.KOM, M.KOM; HAFIZH AL KAUTSAR AIDILOF, ST.,M.Kom',
                'hari' => 'Kamis',
                'jam_mulai' => '08:00',
                'jam_selesai' => '10:30',
                'ruangan' => 'INF-RUANG KULIAH V',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'DESAIN DAN ANALISIS ALGORITMA',
                'dosen' => 'ZAHRATUL FITRI, S.Kom., M.Kom; NUNSINA, ST., M.Kom',
                'hari' => 'Kamis',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => '08.A',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'DESAIN DAN ANALISIS ALGORITMA',
                'dosen' => 'ZAHRATUL FITRI, S.Kom., M.Kom; NUNSINA, ST., M.Kom',
                'hari' => 'Kamis',
                'jam_mulai' => '08:00',
                'jam_selesai' => '10:30',
                'ruangan' => '08.A',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'DESAIN DAN ANALISIS ALGORITMA',
                'dosen' => 'ZAHRATUL FITRI, S.Kom., M.Kom; NUNSINA, ST., M.Kom',
                'hari' => 'Rabu',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => '08.A',
            ],

            // HUMAN COMPUTER INTERACTION
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'HUMAN COMPUTER INTERACTION',
                'dosen' => 'DrFAJRIANA, S. Si., M.Si; SAFWANDI, ST., M.Kom',
                'hari' => 'Jumat',
                'jam_mulai' => '09:00',
                'jam_selesai' => '11:30',
                'ruangan' => 'INF-RUANG KULIAH II',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'HUMAN COMPUTER INTERACTION',
                'dosen' => 'DrFAJRIANA, S. Si., M.Si; SAFWANDI, ST., M.Kom',
                'hari' => 'Rabu',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => '08.A',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'HUMAN COMPUTER INTERACTION',
                'dosen' => 'WAHYU FUADI, ST, M.IT; ROZZI KESUMA DINATA, ST.,M.Eng',
                'hari' => 'Senin',
                'jam_mulai' => '08:00',
                'jam_selesai' => '10:30',
                'ruangan' => 'INF-RUANG KULIAH II',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'HUMAN COMPUTER INTERACTION',
                'dosen' => 'WAHYU FUADI, ST, M.IT; ROZZI KESUMA DINATA, ST.,M.Eng',
                'hari' => 'Senin',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => 'INF-RUANG KULIAH II',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'HUMAN COMPUTER INTERACTION',
                'dosen' => 'DrASRIANDA, S.Kom.,M.Kom; EVA DARNILA, ST.,MT',
                'hari' => 'Rabu',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => 'INF-RUANG KULIAH MTI 1',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'HUMAN COMPUTER INTERACTION',
                'dosen' => 'DrASRIANDA, S.Kom.,M.Kom; EVA DARNILA, ST.,MT',
                'hari' => 'Selasa',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => '08.B',
            ],

            // INTERNET OF THINGS
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'INTERNET OF THINGS',
                'dosen' => 'TAUFIQ, S.T., M.T',
                'hari' => 'Senin',
                'jam_mulai' => '08:00',
                'jam_selesai' => '10:30',
                'ruangan' => 'LAB INFORMATIKA 2',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'INTERNET OF THINGS',
                'dosen' => 'ZAHRATUL FITRI, S.Kom., M.Kom; NUNSINA, ST., M.Kom',
                'hari' => 'Senin',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => 'LAB INFORMATIKA 4',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'INTERNET OF THINGS',
                'dosen' => 'FADLISYAH, S.Si.,MT; Dr. EngMUHAMMAD FIKRY, S.Kom., M.Kom',
                'hari' => 'Selasa',
                'jam_mulai' => '08:00',
                'jam_selesai' => '10:30',
                'ruangan' => 'LAB INFORMATIKA 4',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'INTERNET OF THINGS',
                'dosen' => 'FADLISYAH, S.Si.,MT; Dr. EngMUHAMMAD FIKRY, S.Kom., M.Kom',
                'hari' => 'Selasa',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => 'LAB INFORMATIKA 4',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'INTERNET OF THINGS',
                'dosen' => 'ZAHRATUL FITRI, S.Kom., M.Kom; NUNSINA, ST., M.Kom',
                'hari' => 'Selasa',
                'jam_mulai' => '08:00',
                'jam_selesai' => '10:30',
                'ruangan' => 'LAB INFORMATIKA 3',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'INTERNET OF THINGS',
                'dosen' => 'RISAWANDI, ST.,M.Kom; Dr. EngMUHAMMAD FIKRY, S.Kom., M.Kom',
                'hari' => 'Jumat',
                'jam_mulai' => '14:30',
                'jam_selesai' => '17:00',
                'ruangan' => 'LAB INFORMATIKA 4',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'INTERNET OF THINGS',
                'dosen' => 'ZAHRATUL FITRI, S.Kom., M.Kom; NUNSINA, ST., M.Kom',
                'hari' => 'Senin',
                'jam_mulai' => '08:00',
                'jam_selesai' => '10:30',
                'ruangan' => 'LAB INFORMATIKA 4',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'INTERNET OF THINGS',
                'dosen' => 'MUKHLIS ABD MUTHALIB, ST., M.Eng., Ph.D; RISAWANDI, ST.,M.Kom',
                'hari' => 'Rabu',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => 'LAB INFORMATIKA 4',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'INTERNET OF THINGS',
                'dosen' => 'ZAHRATUL FITRI, S.Kom., M.Kom; NUNSINA, ST., M.Kom',
                'hari' => 'Rabu',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => 'LAB INFORMATIKA 2',
            ],

            // JARINGAN KOMPUTER FUNDAMENTAL
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'JARINGAN KOMPUTER FUNDAMENTAL',
                'dosen' => 'Dr.MUNIRUL ULA, ST.,M.Eng; RIZAL, S.Si, M.IT',
                'hari' => 'Selasa',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => 'LAB INFORMATIKA 1',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'JARINGAN KOMPUTER FUNDAMENTAL',
                'dosen' => 'Dr.MUNIRUL ULA, ST.,M.Eng; RIZAL, S.Si, M.IT',
                'hari' => 'Kamis',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => 'LAB INFORMATIKA 4',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'JARINGAN KOMPUTER FUNDAMENTAL',
                'dosen' => 'Dr.MUNIRUL ULA, ST.,M.Eng; RIZAL, S.Si, M.IT',
                'hari' => 'Kamis',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => 'LAB INFORMATIKA 4',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'JARINGAN KOMPUTER FUNDAMENTAL',
                'dosen' => 'BUSTAMI, S.Si,M.Si; AR RAZI, ST.,M.Cs',
                'hari' => 'Senin',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => 'LAB INFORMATIKA 1',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'JARINGAN KOMPUTER FUNDAMENTAL',
                'dosen' => 'BUSTAMI, S.Si,M.Si; AR RAZI, ST.,M.Cs',
                'hari' => 'Senin',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => 'LAB INFORMATIKA 1',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'JARINGAN KOMPUTER FUNDAMENTAL',
                'dosen' => 'BUSTAMI, S.Si,M.Si; AR RAZI, ST.,M.Cs',
                'hari' => 'Rabu',
                'jam_mulai' => '10:00',
                'jam_selesai' => '13:10',
                'ruangan' => 'LAB INFORMATIKA 4',
            ],

            // PEMROGRAMAN BASIS DATA
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'PEMROGRAMAN BASIS DATA',
                'dosen' => 'MUKTI QAMAL, ST.,M.IT; RINI MEIYANTI, ST.,M.Kom',
                'hari' => 'Selasa',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => 'LAB INFORMATIKA 2',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'PEMROGRAMAN BASIS DATA',
                'dosen' => 'RIZKI SUWANDA, ST.,M.Kom; SAID FADLAN ANSHARI, S.Kom., M.Kom',
                'hari' => 'Selasa',
                'jam_mulai' => '08:00',
                'jam_selesai' => '10:30',
                'ruangan' => 'LAB INFORMATIKA 2',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'PEMROGRAMAN BASIS DATA',
                'dosen' => 'WAHYU FUADI, ST, M.IT; ROZZI KESUMA DINATA, ST.,M.Eng',
                'hari' => 'Selasa',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => 'LAB INFORMATIKA 3',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'PEMROGRAMAN BASIS DATA',
                'dosen' => 'WAHYU FUADI, ST, M.IT; ROZZI KESUMA DINATA, ST.,M.Eng',
                'hari' => 'Kamis',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => 'LAB INFORMATIKA 3',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'PEMROGRAMAN BASIS DATA',
                'dosen' => 'RIZKI SUWANDA, ST.,M.Kom; SAID FADLAN ANSHARI, S.Kom., M.Kom',
                'hari' => 'Senin',
                'jam_mulai' => '08:00',
                'jam_selesai' => '10:30',
                'ruangan' => 'LAB INFORMATIKA 1',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'PEMROGRAMAN BASIS DATA',
                'dosen' => 'DrASRIANDA, S.Kom.,M.Kom; EVA DARNILA, ST.,MT',
                'hari' => 'Selasa',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => 'LAB INFORMATIKA 3',
            ],

            // PEMROGRAMAN WEB LANJUT
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'PEMROGRAMAN WEB LANJUT',
                'dosen' => 'ZARA YUNIZAR, S.Kom.,M.Kom; LIDYA ROSNITA, S.T., M. Kom',
                'hari' => 'Rabu',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => 'LAB INFORMATIKA 3',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'PEMROGRAMAN WEB LANJUT',
                'dosen' => 'ZARA YUNIZAR, S.Kom.,M.Kom; LIDYA ROSNITA, S.T., M. Kom',
                'hari' => 'Rabu',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => 'LAB INFORMATIKA 3',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'PEMROGRAMAN WEB LANJUT',
                'dosen' => 'RIZKI SUWANDA, ST.,M.Kom; SAID FADLAN ANSHARI, S.Kom., M.Kom',
                'hari' => 'Rabu',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => 'LAB INFORMATIKA 1',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'PEMROGRAMAN WEB LANJUT',
                'dosen' => 'RIZKI SUWANDA, ST.,M.Kom; SAID FADLAN ANSHARI, S.Kom., M.Kom',
                'hari' => 'Selasa',
                'jam_mulai' => '08:00',
                'jam_selesai' => '10:30',
                'ruangan' => 'LAB INFORMATIKA 1',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'PEMROGRAMAN WEB LANJUT',
                'dosen' => 'RIZKI SUWANDA, ST.,M.Kom; SAID FADLAN ANSHARI, S.Kom., M.Kom',
                'hari' => 'Selasa',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => 'LAB INFORMATIKA 4',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'PEMROGRAMAN WEB LANJUT',
                'dosen' => 'BUSTAMI, S.Si,M.Si; AR RAZI, ST.,M.Cs',
                'hari' => 'Selasa',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => 'LAB INFORMATIKA 1',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'PEMROGRAMAN WEB LANJUT',
                'dosen' => 'FADLISYAH, S.Si.,MT; Dr. EngMUHAMMAD FIKRY, S.Kom., M.Kom',
                'hari' => 'Senin',
                'jam_mulai' => '10:40',
                'jam_selesai' => '13:10',
                'ruangan' => 'LAB INFORMATIKA 2',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'PEMROGRAMAN WEB LANJUT',
                'dosen' => 'FADLISYAH, S.Si.,MT; Dr. EngMUHAMMAD FIKRY, S.Kom., M.Kom',
                'hari' => 'Senin',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => 'LAB INFORMATIKA 3',
            ],
            [
                'user_id' => $adminId,
                'mata_kuliah' => 'PEMROGRAMAN WEB LANJUT',
                'dosen' => 'RIZKI SUWANDA, ST.,M.Kom; T. SUKMA ACHRIADI SUKIMAN, S.Kom., M.Kom',
                'hari' => 'Senin',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruangan' => 'LAB INFORMATIKA 4',
            ],
        ];

        foreach ($daftarJadwal as $jadwal) {
            Jadwal::create($jadwal);
        }
    }
}
